### ISSUE TITLE
[FIX]: Project Structure

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/Weather-app#12]
Fix the project structure with the relevant folder structure.
This is issue is for non-coders.

![image](https://github.com/devjainofficial/Weather-app/assets/69387311/cb8ae0fe-d16d-4cd6-aac8-12cb1f66ef51)

**Comment by dyarawilliams** [comment]
Hello, I'd like to complete this task for the hacktoberfest event please?

**Comment by devjainofficial** [comment]
Share the screenshot of working project after completion of task

**Comment by dyarawilliams** [comment]
Okay thank you @devjainofficial

**Comment by dyarawilliams** [comment]
Is this what you're asking for? @devjainofficial 

![Screenshot 2023-10-21 155210](https://github.com/devjainofficial/Weather-app/assets/15236104/dd8a9fdd-dd37-4bfb-9d52-36f129e0dcf5)

**Comment by devjainofficial** [comment]
Yes @dyarawilliams , screenshot looking good

**Comment by dyarawilliams** [comment]
Completed PR #14

**Comment by devjainofficial** [comment]
Thanks for contributing.

**Comment by devjainofficial** [comment]
I have checked the website UI, there is an error in the code because you didn't specify the path correctly. Recheck the code and share the working website UI screenshot.

**Comment by dyarawilliams** [comment]
Okay sorry getting right to it now @devjainofficial

**Comment by dyarawilliams** [comment]
![Screenshot 2023-10-24 014445](https://github.com/devjainofficial/Weather-app/assets/15236104/2fb89cef-3a8d-4a8b-962d-44fbfb315560)

**Comment by devjainofficial** [comment]
Pull request merged.
