### ISSUE TITLE
Add more features in the application using weather api

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/Weather-app#17]
Share the screenshot of the working website.

**Comment by GriffinAnnshual** [comment]
@devjainofficial Assign me this issue please?

**Comment by GriffinAnnshual** [comment]
@devjainofficial Adding air quality index would be a nice feature, right?

**Comment by GriffinAnnshual** [comment]
![screenshot](https://github.com/devjainofficial/Weather-app/assets/77448860/d22b713a-206b-4a07-8106-142cfd9cb8c1)
I have attached the screenshot. Here please take a look.

**Comment by devjainofficial** [comment]
Sorry, I forgot I already added the air quality index. Please add something different that is not on the current website. 
![image](https://github.com/devjainofficial/Weather-app/assets/69387311/67da1033-80f7-4a44-bffa-84c2fcb530aa)
