### ISSUE TITLE
Create a Footer

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/Weather-app#2]
Create a better & attractive footer. Something colorful that relates to the whole application and you can use any icons too.

![image](https://github.com/devjainofficial/Weather-app/assets/69387311/cd5aa482-9fb0-4606-a671-7e5ef490572f)

**Comment by ankman007** [comment]
@devjainofficial Working on this issue. Please assign it to me.

**Comment by amitesh-183** [comment]
I would Like to contribute, If still not done??
