### ISSUE TITLE
Add the decorative footer similar to the website

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/Weather-app#20]
Share the screenshot of the working website.

**Comment by BkPankaj** [comment]
Hey @devjainofficial can you tell me what things you need in your footer. I am interested in this project, and I want to work on it.

**Comment by devjainofficial** [comment]
Basically, I majorly want something highly UI-based decorative footer that can fit with my website and some of the details of my social media accounts, copyright, etc, and you can also add something more that looks good.

**Comment by BkPankaj** [comment]
Got it! @devjainofficial Thanks for the clarification. Please assign this issue to me.

**Comment by BkPankaj** [comment]
@devjainofficial please verify and merge the changes
