### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/Weather-app#21]
Add the dark mode using toggle button.
![image](https://github.com/devjainofficial/Weather-app/assets/69387311/6adbd7af-c1ee-4518-b7ba-8f3355b1f75a)

**Comment by Varlight** [comment]
@devjainofficial  I would love to work on this issue, assign me to it.

**Comment by Varlight** [comment]
@devjainofficial where should the toggle be ? I am done with other stuff

**Comment by devjainofficial** [comment]
Place it in the header, and make sure dark and light mode text color should be different too.

**Comment by Varlight** [comment]
@devjainofficial is there any chat forum for this project, I am having some troubles would like to discuss about them

**Comment by devjainofficial** [comment]
Open to help

**Comment by Varlight** [comment]
![image](https://github.com/devjainofficial/Weather-app/assets/102368642/a48dbc93-f269-41b8-b24d-8c620af96127)
![image](https://github.com/devjainofficial/Weather-app/assets/102368642/4b980d55-6889-4724-8fa7-c2b4d3226b1e)

I couldn't position the toggle properly, and its interfering with the search box.

**Comment by Varlight** [comment]
@devjainofficial

**Comment by devjainofficial** [comment]
I saw your code it has a positioning problem. Make it responsive too.

**Comment by abhijeetsharnagat** [comment]
Does this works? 

Netlify link - https://updated-weather-app.netlify.app/

Dark mode- 

![darkmode](https://github.com/devjainofficial/Weather-app/assets/108009757/ba925ac1-5291-488b-b488-2fca4165f946)

Light mode -

![ligh mode](https://github.com/devjainofficial/Weather-app/assets/108009757/c0cccabb-65be-441f-a51a-6a6adf91150a)
