### ISSUE TITLE
Search the bug

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/Weather-app#22]
Search the bug and report me by creating a txt file, and add your searched bug there.

**Comment by shivang21007** [comment]
@devjainofficial  I resolved the bug-issue.
it is nothing just you are using listener in wrong way- 

![image](https://github.com/devjainofficial/Weather-app/assets/98748694/5113f433-d85a-4673-979a-45577d9d3db3)

this event listener listen when anykey press down on keyboard so as soon as user start typer name of city , it start listening everytime when any letter pressed.
the motive to solve it only listen when enter keypressed by user.
so this is my solution -
![image](https://github.com/devjainofficial/Weather-app/assets/98748694/f750fcad-8e3d-4ed4-9f45-38bd7dcba826)

also added a feature by making icon as button so if someone click on search icon it will also work.
I am raising PR as final solution.

**Comment by devjainofficial** [comment]
Thankyou for your contribution.
