### ISSUE TITLE
Bug with the footer.

### ISSUE THREAD

**Issue by therahulchaurasia** [devjainofficial/Weather-app#31]
Hey @devjainofficial, I just saw the newly added footer and I think it's awesome and it suits the project very well.
However, just as I was trying to run the code I saw a few issues that were introduced with this feature.
Firstly, I would like to point the error that occurs when you try to run the new code.
![image](https://github.com/devjainofficial/Weather-app/assets/90378272/4373f2fd-1bea-4edd-be64-2d8407f8316c)
This occurs because the old copyright has been commented in the index file we try to access it in js. 
Fix: It will be a simple fix and I can do it for you.

Another issue 
The footer does not appear at the bottom of the content, instead it takes an entire screens height and calculates the bottom.
![image](https://github.com/devjainofficial/Weather-app/assets/90378272/1a599f06-4b96-4553-a174-deaaffb9a9b4)
Fix: I'll need to change the CSS for the footer and it will work fine.

**Comment by therahulchaurasia** [comment]
Can you please assign this issue to me so I can work on fixing the issues mentioned above.

**Comment by devjainofficial** [comment]
Thankyou for addressing this bug, please do it

**Comment by therahulchaurasia** [comment]
Hey @devjainofficial I think this issue can be closed because my PR fixes the above issue and I have attached the screenshot for the same.

**Comment by devjainofficial** [comment]
sure
