### ISSUE TITLE
[BUG]: AQI Not Vsibile

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/Weather-app#35]
![image](https://github.com/devjainofficial/Weather-app/assets/69387311/3d3c28af-c114-4313-8547-9d21a4a09161)
Resolve the Air Quality Index Issue in this card. Evertime its showing NaN. Check the Issue and resolve it.

**Comment by LalitDeore** [comment]
i can solve this error can you please assign this task to me?

**Comment by devjainofficial** [comment]
Thank you For your contribution.
