### ISSUE TITLE
Bug: Need to Fix the search box.

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/Weather-app#39]
## Need to Fix the search box with respect to the search icon in the search box

**Screenshot**
![image](https://github.com/user-attachments/assets/70a9061f-97fe-4dd9-bc38-5f5b989dee0e)

**Labels:**
- bug
- frontend
- high priority

**Comment by EspeonIV** [comment]
Hey @devjainofficial  can you assign this to me?

**Comment by devjainofficial** [comment]
Hello @EspeonIV assigned the task to you. Please start working on it.

**Comment by EspeonIV** [comment]
Pull request related to this issue is here, https://github.com/devjainofficial/Weather-app/pull/45
