### ISSUE TITLE
[FEAT]: Add Relevant Favicon to Website

### ISSUE THREAD

**Issue by ankman007** [devjainofficial/Weather-app#4]
### Issue Description:
Currently, our weather application lacks a favicon, which is a small icon displayed in the browser tab. Adding a favicon not only enhances the visual identity of the website but also provides users with a recognizable symbol when they have multiple tabs open. 

#### Proposed Changes:
- **Favicon Design:** Design a simple and clear favicon that represents our weather application. Consider using weather-related symbols, such as a sun, cloud, or thermometer, to make it relevant to the application's theme.
- **Implementation:** Add the favicon to the website's `<head>` section in the HTML file. Ensure the favicon is appropriately sized and optimized for various devices and screen resolutions.
- **Testing:** Test the website in different browsers to confirm the favicon is displayed correctly in all of them. Also, verify its visibility on both desktop and mobile devices.

**Comment by pranavjainjs** [comment]
I have generated a few images using AI generator. Let me know if they work.
![dxIHd6LewdFfpCosdoCd--grid](https://github.com/devjainofficial/Weather-app/assets/95164530/bde68c10-e221-4c52-b747-b564c8e07cbe)
![OUdKq90SJDatOejd4Ymf--1--faiws](https://github.com/devjainofficial/Weather-app/assets/95164530/6a31f512-633c-4a2c-bc04-04d288831c76)

**Comment by devjainofficial** [comment]
The last one is looking good, add it to the website

**Comment by devjainofficial** [comment]
Thankyou @DeepRahangdale for your contribution but this issue was assigned to @pranavjainjs that's why I'm merging his pull request, @DeepRahangdale you can contribute to other issues.
