### ISSUE TITLE
refactor: Refactor Required in [main.js]

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/Weather-app#41]
**Description:**  
The code in `[main.js]` needs refactoring to improve readability for new developers. Adding comments will help them understand the functionality better.

---

**Reason for Refactor:**  
- **Clarity:** The current code structure can be confusing for newcomers.
- **Documentation:** It lacks comments that explain the key parts of the code.

---

**Proposed Changes:**  
1. Simplify complex code.
2. Add comments to explain key functions and logic.
3. Use clear naming conventions.

---

**Benefits of the Refactor:**  
- Makes the code easier to read and understand.
- Helps onboard new contributors more effectively.

---

**Label:**  
`refactor`

**Comment by ShobhitShrivastava089** [comment]
@devjainofficial Assign it to me.
