### ISSUE TITLE
refactor: Refactor Required in style.css

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/Weather-app#44]
Description:
The code in style.css needs refactoring to improve readability for new developers. Adding comments will help them understand the styles better.

Reason for Refactor:

Clarity: The current CSS structure can be confusing for newcomers.
Documentation: There are minimal comments explaining the styles.
Specific Areas for Refactor:

File: style.css

Proposed Changes:

Organize CSS rules for better readability and maintainability.
Add comments to clarify the purpose of complex styles.
Benefits of the Refactor:

Enhances code readability and makes onboarding easier for new contributors.
Provides better documentation of the styles used.

Label:
refactor

**Comment by shahzdvp** [comment]
i would like to work on this

**Comment by devjainofficial** [comment]
@shahzdvp Assigned the task to you.

**Comment by shahzdvp** [comment]
iam unable to work on this ,sorry for the inconvenience

**Comment by RajdeepDey010** [comment]
Hi Maintainer,
Can you assign me this work.

**Comment by devjainofficial** [comment]
Hey @RajdeepDey010, assigned you the task.
