### ISSUE TITLE
Enhancement: Create Good Looking Modal which matches web application's UI

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/Weather-app#50]
![image](https://github.com/user-attachments/assets/a2148bc4-c0a5-45d4-ac48-6cb9127e049f)

Fix the Color Mismatch and enhance the UI with respect to the application.

Can take help from #47

**Comment by n-keerthi-gayathri** [comment]
@devjainofficial please assign me

**Comment by devjainofficial** [comment]
@n-keerthi-gayathri it's an urgent issue, please resolve it quick.

**Comment by n-keerthi-gayathri** [comment]
![image](https://github.com/user-attachments/assets/448fb047-4200-4d4f-85ed-5cfc1b108aa0)
I made this, tell me if you need anything to be modified

**Comment by devjainofficial** [comment]
Looks good, please add the pull request.
