### ISSUE TITLE
The Dialog box is blank it is not showing any data.

### ISSUE THREAD

**Issue by PankajR007** [devjainofficial/Weather-app#51]
When the user visits/reloaded the page, the Dialog box is coming blank with no data inside it in light mode. 

Issue screen shot 
![image](https://github.com/user-attachments/assets/6aa41d91-45a0-4737-95b1-74daa96a3c83)

@devjainofficial  please assign this issue to me under the hacktofrebest label.

**Comment by devjainofficial** [comment]
Hello @PankajR007, Already created the issue for the same. #50

**Comment by devjainofficial** [comment]
Thankyou for your interest, You can contribute on other issues
