### ISSUE TITLE
Fix the Air Quality Card UI

### ISSUE THREAD

**Issue by PankajR007** [devjainofficial/Weather-app#52]
Fix the Air Quality Card UI, the words inside the card are not clearly visible in dark color background. To fix this  I will make it glassmorphisim effect.

so that UI looks good.

screenshot
 
![image](https://github.com/user-attachments/assets/7a94124d-5d8c-4f2a-a526-7411087a4923)

@devjainofficial please assign this to me under the hacktoberfest label.

**Comment by viratde** [comment]
Hey @devjainofficial, Can you assign this to me?

**Comment by mrhat05** [comment]
can you assign me for this?

**Comment by PankajR007** [comment]
@devjainofficial can you please assign this to me ?

**Comment by devjainofficial** [comment]
Hello @mrhat05, this issue was created by @PankajR007, So let him first try to solve it.
@mrhat05 you can solve other issues too.
Thankyou for showing your interest.

**Comment by mrhat05** [comment]
@devjainofficial Ok.
 Thankyou

**Comment by devjainofficial** [comment]
@PankajR007 Is there Any update?
